'use client';

import { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { Download, Loader2 } from 'lucide-react';
import { Roadmap } from '@/types';

interface ExportButtonProps {
  roadmap: Roadmap;
}

export function ExportButton({ roadmap }: ExportButtonProps) {
  const [isExporting, setIsExporting] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const handleExport = async () => {
    if (!roadmap) return;
    setIsExporting(true);

    try {
      const jsPDF = (await import('jspdf')).default;
      const doc = new jsPDF();

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let yPos = margin;

      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text(roadmap.title, margin, yPos);
      yPos += 12;

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      const descLines = doc.splitTextToSize(roadmap.description, contentWidth);
      doc.text(descLines, margin, yPos);
      yPos += descLines.length * 5 + 8;

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Estimated Duration: ${roadmap.totalDuration}`, margin, yPos);
      yPos += 15;

      doc.setTextColor(0, 0, 0);
      doc.setDrawColor(0, 0, 0);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 10;

      roadmap.steps.forEach((step, index) => {
        if (yPos > 250) {
          doc.addPage();
          yPos = margin;
        }

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(`${step.step}. ${step.title}`, margin, yPos);
        yPos += 8;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        const stepLines = doc.splitTextToSize(step.description, contentWidth);
        doc.text(stepLines, margin, yPos);
        yPos += stepLines.length * 5 + 5;

        if (step.resources.length > 0) {
          doc.setFontSize(9);
          doc.setTextColor(100, 100, 100);
          doc.text('Resources:', margin, yPos);
          yPos += 5;

          doc.setTextColor(0, 0, 0);
          step.resources.forEach((resource, rIdx) => {
            if (yPos > 270) {
              doc.addPage();
              yPos = margin;
            }

            const resourceText = `  ${rIdx + 1}. ${resource.title}`;
            const resourceLines = doc.splitTextToSize(resourceText, contentWidth - 10);
            doc.text(resourceLines, margin, yPos);
            yPos += resourceLines.length * 4 + 2;

            doc.setTextColor(0, 98, 255);
            const urlLines = doc.splitTextToSize(`     ${resource.url}`, contentWidth - 10);
            doc.text(urlLines, margin, yPos);
            yPos += urlLines.length * 4;
            doc.setTextColor(0, 0, 0);
          });
        }

        yPos += 10;

        if (index < roadmap.steps.length - 1 && yPos < 260) {
          doc.setDrawColor(200, 200, 200);
          doc.line(margin, yPos, pageWidth - margin, yPos);
          yPos += 10;
        }
      });

      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      const footerY = doc.internal.pageSize.getHeight() - 10;
      doc.text('Generated by Free Course Finder', margin, footerY);

      doc.save(`${roadmap.topic.replace(/[^a-z0-9]/gi, '_')}_roadmap.pdf`);
    } catch (error) {
      console.error('PDF export error:', error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button
      onClick={handleExport}
      disabled={isExporting}
      variant="secondary"
      className={cn('gap-2', isExporting && 'opacity-70')}
    >
      {isExporting ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          Export PDF
        </>
      )}
    </Button>
  );
}
